# Generated by Django 4.1.3 on 2022-12-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke_sim_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedpoke',
            name='img_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
